org.aibles.auth.utils.exception.ResourceNotFoundException=Resource {0} with id {1} can not be found.
org.aibles.auth.utils.exception.EmailAlreadyExistsException=Email {0} already exists.
org.aibles.auth.utils.exception.UserNameInValidException=Username {0} is invalid.
org.aibles.auth.utils.exception.PasswordNotMatchException=Password does not match the confirmPassword.

